version: '3'


services:
  mariadb:
    image: mariadb:10.2
    ports:
      - 3307:3306
    environment:
      #MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ratelimitdb